stages:
    - test

.test:
    stage: test
    before_script:
        - pip install -e ".[test,ipython]"
    script:
        - mypy kong
        - flake8 kong
        - pytest --cov=kong --log-level DEBUG
        - coverage html
    artifacts:
        paths:
            - htmlcov

format:
    image: python:3.7
    before_script:
        - pip install -e ".[dev]"
    script:
        - black --check kong

python-latest:
    extends: .test
    image: python:latest

python3.7:
    extends: .test
    image: python:3.7

python3.6:
    extends: .test
    image: python:3.6
