stages:
    - test

.test:
    stage: test
    before_script:
        - pip install -e ".[dev]"
    script:
        - pytest --cov=kong
        - coverage html
    artifacts:
        paths:
            - htmlcov

python3.7:
    extends: .test
    image: python:3.7

python3.6:
    extends: .test
    image: python:3.6

python3.5:
    extends: .test
    image: python:3.5

python3.4:
    extends: .test
    image: python:3.4
