language: python
python:
  - '3.6'
  - '3.7'

install: pip install tox-travis

script: tox

after_success:
  - codecov


jobs:
  include:
    - stage: deploy
      script: skip     # usually you do not want to rerun any tests
      python: '3.7'
      deploy:
          provider: pypi
          user: "paulgessinger"
          password:
            secure: 02xFsY9TNga66eDJnNqhL4SgC0PKsx/zUJXRz51zg6aFT61s/9ZlZbVi7v3OjBRc0qR/3zCIeKmfefIzcLjjqW7OkOyJBvX1sbPyaghDLdv3aJXLfWAKn5tlrZuyfZO1Ad5B3+vMhhUkdcpKlkBrOneWLGCFkg3gf0t8P9ISgb3yNvPKXpelRd2aQM6nTJ1N1x5FnxK4PvfWYp5zNwpzBgPXOTMFSgdTpgeG+hJ+nNAG7BluxtgrP7YCsL0ZpiHrcL3IHE9n9Qb8fMWvnwSe/yA3l2+NYga2ruG3xERpwq9pTuAA/W2qkqU3Ps+4zqWc4ZvKCfqTMA7iD7EA4CX/L74cCQeCis3u7b0VRR8emrJUPMSZOGKKfdXGOJ/qBeyFdj7tXSsiru93F6sm2FutfxSbeohsT7Wn4dWcm1FMEpo2JLLDoaj4HgodanOcZV7AjugfcBE5kZOx/wX0xJ5EpIzZIWvDAD9PeF++UmqJzTwYCVOJH14L7k+ANLTOiua7VN6h+F5fOrJNSxIJTG8cSKpQk0gtMtYpie2PezqvCvwEVzuRBfvUQt5zSJt2TJhZL5tkUE8UEhf2Dl4gT9gLH9QvfzcihRL1to8uwoLo+zDN9tV3EtcBtrlC1L8WTDiWbAnQnlztj1xcugtOd2jp6S5gwqOB1y32eIKqUzYFdSE=
          on:
              tags: true
          skip_existing: true
          distributions: "sdist bdist_wheel"
