language: python
python:
  - '3.6'
  - '3.7'

install: pip install tox-travis

script: tox

after_success:
  - codecov


jobs:
  include:
    - stage: deploy
      script: skip     # usually you do not want to rerun any tests
      python: '3.7'
      deploy:
          provider: pypi
          edge: true
          user: "paulgessinger"
          on:
              tags: true
          skip_existing: true
          distributions: "sdist bdist_wheel"
