language: python
python:
  - "3.6"
  - "3.7"
  - "3.8-dev"

# command to install dependencies
install:
  - pip install -e ".[test,ipython]"

script:
  - mypy kong
  - flake8 kong
  - pytest --cov=kong --log-level DEBUG
  - coverage html

jobs:
  include:
    - stage: format
      script:
        - black --check kong
