language: python
python:
  - "3.6"
  - "3.7"

# command to install dependencies
install:
  - pip install -e ".[test,ipython]"

script:
  - mypy kong
  - flake8 kong
  - pytest --cov-report=xml --cov=kong --log-level DEBUG
  - coverage html

env: 
  - CODECOV_TOKEN="8f83285c-28b6-411c-a17c-55c0b607da5f"

jobs:
  include:
    - stage: format
      script:
        - black --check kong
