language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'

git:
  depth: false

install: pip install tox-travis codecov

script: tox

after_success:
  - codecov


jobs:
  include:
    - stage: deploy
      script: skip
      python: '3.7'
      before_deploy: pip install .
      after_success:
      deploy:
          provider: pypi
          user: "paulgessinger"
          password:
            secure: EF2wm9KZW84wf8I8tNa0lQ/9YgEsnPTrScwJJ6YMMg1iO08E+/qq1LcMshXa9fGiCjQIh0zC4kxcrTik1FpcLkztK12++xzRwQN9lGP9VnnpCJPAQeMN2qzL5P7OVzEbjwgY5Ans8WfDG80IeYxurmfMyJzCEddeOZ6HLK/EV6EsYkK29HRUKNXOf01VS/jRv1rm2ZdbLQshJZaIboFJcE1t+KryWnh1Bca8tQf2XjPBv2K6KYnIQy30QhA7nfG+L9qZcAqjQgwY9/oCJ1ve6l7zRLZraVjiaPyQrzU00haL5+4lpTdN1Br9MV9s/0SQZ9CinHWfb3xg/VFlaxKfmc5S+jIpjJH+Ibph1wfiS6UK/vaEZpO1YwBgFpmY1KaOR/GV60ltK3/T+HiFSuEyLf1SW/jbsTapUsPHxphhBNJnoCeHNNVl0yx6Wx9rsD/aqJ8QpfiFSiHmXE71j7OeeNQ1EOcbD2iy6iaKJT75CbvzK6QHTCQJ8F+IUpKAYrNUdlz0XCxzWa5Tym6tiLeqSdcRo8ue4wc1OL7qgAu+iTgzOswns1504YKTzljB0hFpOeUecVVYRJIJQS3opDUwB3hisdkf0wJqUkevETdb2L5DPsTmqqVQ/m01ZQpQAWnjQfXLT94nMxFC+5ZkNd/XpGEnTmLsnMl98oElqoxnbqM=
          on:
              tags: true
          skip_existing: true
          distributions: "sdist bdist_wheel"
