result = (
    1595360293,
    "https://bigpanda.cern.ch/tasks/?json=1&datasets=True&limit=10000&jeditaskid=21948780%7C21948716%7C21956507%7C21953913%7C21962217",
    [
        {
            "jeditaskid": 21962217,
            "taskname": "user.pagessin.r015.grid_data_p4030.00351455/",
            "status": "scouting",
            "username": "Paul Gessinger-Befurt",
            "creationdate": "2020-07-21 19:19:56",
            "modificationtime": "2020-07-21 19:20:11",
            "reqid": 1124,
            "oldstatus": "",
            "cloud": "",
            "site": "",
            "starttime": "2020-07-21 19:19:56",
            "endtime": None,
            "frozentime": None,
            "prodsourcelabel": "user",
            "workinggroup": "",
            "vo": "atlas",
            "corecount": 1,
            "tasktype": "anal",
            "processingtype": "panda-client-1.4.32-jedi-run",
            "taskpriority": 1001,
            "currentpriority": 1000,
            "architecture": "x86_64-centos7-gcc8-opt@centos7",
            "transuses": "Atlas-21.2.121",
            "transhome": "AnalysisTransforms-AnalysisBase_21.2.121",
            "transpath": "runGen-00-00-02",
            "lockedby": "",
            "lockedtime": None,
            "termcondition": "Linux-3.10.0-1127.13.1.el7.x86_64-x86_64-with-centos-7.8.2003-Core",
            "splitrule": "US=2,MF=200,RR=1,DE=rucio,IL=1,MO=1,UB=1,IT=1,IA=1,LS=3",
            "walltime": 0,
            "walltimeunit": "",
            "outdiskcount": 500,
            "outdiskunit": "kB",
            "workdiskcount": 0,
            "workdiskunit": "",
            "ramcount": 2000,
            "ramunit": "MBPerCore",
            "iointensity": None,
            "iointensityunit": "",
            "workqueue_id": 100,
            "progress": None,
            "failurerate": None,
            "errordialog": "",
            "countrygroup": "de",
            "parent_tid": 21962217,
            "eventservice": "ordinary",
            "ticketid": "",
            "ticketsystemtype": "",
            "statechangetime": "2020-07-21 19:20:11",
            "superstatus": "submitting",
            "campaign": "",
            "gshare": "User Analysis",
            "cputime": None,
            "cputimeunit": "",
            "basewalltime": 600,
            "cpuefficiency": 90,
            "nucleus": "",
            "ttcrequested": None,
            "ttcpredicted": None,
            "ttcpredictiondate": None,
            "resquetime": None,
            "requesttype": "",
            "resourcetype": "SCORE",
            "usejumbo": "",
            "diskio": None,
            "diskiounit": "",
            "container_name": "",
            "totevrem": 2915859,
            "dsinfo": {
                "nfiles": 49,
                "nfilesfinished": 0,
                "nfilesfailed": 0,
                "pctfinished": 0,
                "pctfailed": 0,
            },
            "totev": 2915859,
            "datasets": [
                {
                    "jeditaskid": 21962217,
                    "datasetid": 322118149,
                    "datasetname": "data18_13TeV:data18_13TeV.00351455.physics_Main.deriv.DAOD_SUSY6.r11570_r11571_p3946_p4030_tid19964694_00",
                    "type": "input",
                    "creationtime": "2020-07-21T19:19:57",
                    "modificationtime": "2020-07-21T19:19:57",
                    "vo": "atlas",
                    "cloud": "",
                    "site": "",
                    "masterid": None,
                    "provenanceid": None,
                    "containername": "data18_13TeV.00351455.physics_Main.deriv.DAOD_SUSY6.r11570_r11571_p3946_p4030",
                    "status": "ready",
                    "state": "closed",
                    "statechecktime": "2020-07-21T19:19:58",
                    "statecheckexpiration": None,
                    "frozentime": None,
                    "nfiles": 49,
                    "nfilestobeused": 42,
                    "nfilesused": 42,
                    "nevents": 2915859,
                    "neventstobeused": 0,
                    "neventsused": 0,
                    "lockedby": "",
                    "lockedtime": None,
                    "nfilesfinished": 0,
                    "nfilesfailed": 0,
                    "attributes": "",
                    "streamname": "IN",
                    "storagetoken": "",
                    "destination": "",
                    "nfilesonhold": 0,
                    "templateid": None,
                }
            ],
        },
        {
            "jeditaskid": 21956507,
            "taskname": "user.pagessin.r014.grid_data_p4030.00363738/",
            "status": "broken",
            "username": "Paul Gessinger-Befurt",
            "creationdate": "2020-07-21 13:44:56",
            "modificationtime": "2020-07-21 17:33:03",
            "reqid": 1078,
            "oldstatus": "",
            "cloud": "",
            "site": "",
            "starttime": "2020-07-21 13:44:57",
            "endtime": "2020-07-21T17:33:03",
            "frozentime": None,
            "prodsourcelabel": "user",
            "workinggroup": "",
            "vo": "atlas",
            "corecount": 1,
            "tasktype": "anal",
            "processingtype": "panda-client-1.4.32-jedi-run",
            "taskpriority": 1001,
            "currentpriority": 1000,
            "architecture": "x86_64-centos7-gcc8-opt@centos7",
            "transuses": "Atlas-21.2.121",
            "transhome": "AnalysisTransforms-AnalysisBase_21.2.121",
            "transpath": "runGen-00-00-02",
            "lockedby": "",
            "lockedtime": "2020-07-21T17:33:02",
            "termcondition": "Linux-3.10.0-1127.13.1.el7.x86_64-x86_64-with-centos-7.8.2003-Core",
            "splitrule": "US=2,MF=200,RR=1,DE=rucio,IL=1,MO=1,UB=1,IT=1,IA=1,LS=3",
            "walltime": 0,
            "walltimeunit": "kSI2kseconds",
            "outdiskcount": 500,
            "outdiskunit": "kB",
            "workdiskcount": 0,
            "workdiskunit": "",
            "ramcount": 2000,
            "ramunit": "MBPerCore",
            "iointensity": None,
            "iointensityunit": "",
            "workqueue_id": 100,
            "progress": None,
            "failurerate": None,
            "errordialog": "no scout jobs succeeded",
            "countrygroup": "de",
            "parent_tid": 21956507,
            "eventservice": "ordinary",
            "ticketid": "",
            "ticketsystemtype": "",
            "statechangetime": "2020-07-21 17:33:03",
            "superstatus": "broken",
            "campaign": "",
            "gshare": "User Analysis",
            "cputime": None,
            "cputimeunit": "",
            "basewalltime": 600,
            "cpuefficiency": 90,
            "nucleus": "",
            "ttcrequested": None,
            "ttcpredicted": None,
            "ttcpredictiondate": None,
            "resquetime": "2020-07-21T15:49:46",
            "requesttype": "",
            "resourcetype": "SCORE",
            "usejumbo": "",
            "diskio": None,
            "diskiounit": "",
            "container_name": "",
            "totevrem": 2926110,
            "dsinfo": {
                "nfiles": 40,
                "nfilesfinished": 0,
                "nfilesfailed": 39,
                "pctfinished": 0,
                "pctfailed": 97,
            },
            "totev": 2926110,
            "datasets": [
                {
                    "jeditaskid": 21956507,
                    "datasetid": 322065798,
                    "datasetname": "data18_13TeV:data18_13TeV.00363738.physics_Main.deriv.DAOD_SUSY6.r11570_r11571_p3946_p4030_tid19965004_00",
                    "type": "input",
                    "creationtime": "2020-07-21T13:44:57",
                    "modificationtime": "2020-07-21T17:33:03",
                    "vo": "atlas",
                    "cloud": "",
                    "site": "",
                    "masterid": None,
                    "provenanceid": None,
                    "containername": "data18_13TeV.00363738.physics_Main.deriv.DAOD_SUSY6.r11570_r11571_p3946_p4030",
                    "status": "failed",
                    "state": "closed",
                    "statechecktime": "2020-07-21T13:45:05",
                    "statecheckexpiration": None,
                    "frozentime": None,
                    "nfiles": 40,
                    "nfilestobeused": 40,
                    "nfilesused": 39,
                    "nevents": 2926110,
                    "neventstobeused": 0,
                    "neventsused": 0,
                    "lockedby": "",
                    "lockedtime": None,
                    "nfilesfinished": 0,
                    "nfilesfailed": 39,
                    "attributes": "",
                    "streamname": "IN",
                    "storagetoken": "",
                    "destination": "",
                    "nfilesonhold": 0,
                    "templateid": None,
                }
            ],
        },
        {
            "jeditaskid": 21953913,
            "taskname": "user.pagessin.r013.mc_signal_p4029.449825",
            "status": "failed",
            "username": "Paul Gessinger-Befurt",
            "creationdate": "2020-07-21 08:43:24",
            "modificationtime": "2020-07-21 09:53:50",
            "reqid": 1010,
            "oldstatus": "",
            "cloud": "",
            "site": "",
            "starttime": "2020-07-21 08:43:25",
            "endtime": "2020-07-21T09:53:50",
            "frozentime": None,
            "prodsourcelabel": "user",
            "workinggroup": "",
            "vo": "atlas",
            "corecount": 1,
            "tasktype": "anal",
            "processingtype": "panda-client-1.4.32-jedi-run",
            "taskpriority": 1001,
            "currentpriority": 1000,
            "architecture": "x86_64-centos7-gcc8-opt@centos7",
            "transuses": "Atlas-21.2.121",
            "transhome": "AnalysisTransforms-AnalysisBase_21.2.121",
            "transpath": "runGen-00-00-02",
            "lockedby": "",
            "lockedtime": "2020-07-21T09:53:46",
            "termcondition": "Linux-3.10.0-1127.13.1.el7.x86_64-x86_64-with-centos-7.8.2003-Core",
            "splitrule": "US=1,MF=200,RR=1,DE=rucio,IL=1,MO=1,UB=1,IT=1,IA=1,LS=3",
            "walltime": 0,
            "walltimeunit": "",
            "outdiskcount": 500,
            "outdiskunit": "kB",
            "workdiskcount": 0,
            "workdiskunit": "",
            "ramcount": 2000,
            "ramunit": "MBPerCore",
            "iointensity": None,
            "iointensityunit": "",
            "workqueue_id": 100,
            "progress": None,
            "failurerate": None,
            "errordialog": "",
            "countrygroup": "de",
            "parent_tid": 21953913,
            "eventservice": "ordinary",
            "ticketid": "",
            "ticketsystemtype": "",
            "statechangetime": "2020-07-21 09:53:50",
            "superstatus": "failed",
            "campaign": "",
            "gshare": "User Analysis",
            "cputime": None,
            "cputimeunit": "",
            "basewalltime": 600,
            "cpuefficiency": 90,
            "nucleus": "",
            "ttcrequested": None,
            "ttcpredicted": None,
            "ttcpredictiondate": None,
            "resquetime": None,
            "requesttype": "",
            "resourcetype": "SCORE",
            "usejumbo": "",
            "diskio": None,
            "diskiounit": "",
            "container_name": "",
            "totevrem": 20872,
            "dsinfo": {
                "nfiles": 5,
                "nfilesfinished": 0,
                "nfilesfailed": 5,
                "pctfinished": 0,
                "pctfailed": 100,
            },
            "totev": 20872,
            "datasets": [
                {
                    "jeditaskid": 21953913,
                    "datasetid": 322031575,
                    "datasetname": "mc16_13TeV:mc16_13TeV.449825.MGPy8EG_A14N23LO_C1C1_HiggsinoLLP_200_0p2_MET50.deriv.DAOD_SUSY6.e7685_e5984_s3475_r11620_r11567_p4029_tid19964251_00",
                    "type": "input",
                    "creationtime": "2020-07-21T08:43:25",
                    "modificationtime": "2020-07-21T09:53:50",
                    "vo": "atlas",
                    "cloud": "",
                    "site": "",
                    "masterid": None,
                    "provenanceid": None,
                    "containername": "mc16_13TeV.449825.MGPy8EG_A14N23LO_C1C1_HiggsinoLLP_200_0p2_MET50.deriv.DAOD_SUSY6.e7685_e5984_s3475_r11620_r11567_p4029",
                    "status": "failed",
                    "state": "closed",
                    "statechecktime": "2020-07-21T08:43:41",
                    "statecheckexpiration": None,
                    "frozentime": None,
                    "nfiles": 5,
                    "nfilestobeused": 5,
                    "nfilesused": 5,
                    "nevents": 20872,
                    "neventstobeused": 0,
                    "neventsused": 0,
                    "lockedby": "",
                    "lockedtime": None,
                    "nfilesfinished": 0,
                    "nfilesfailed": 5,
                    "attributes": "",
                    "streamname": "IN",
                    "storagetoken": "",
                    "destination": "",
                    "nfilesonhold": 0,
                    "templateid": None,
                }
            ],
        },
        {
            "jeditaskid": 21948780,
            "taskname": "user.pagessin.r011.grid_data_p4030.00349114/",
            "status": "done",
            "username": "Paul Gessinger-Befurt",
            "creationdate": "2020-07-20 19:50:27",
            "modificationtime": "2020-07-21 02:47:25",
            "reqid": 171,
            "oldstatus": "",
            "cloud": "",
            "site": "",
            "starttime": "2020-07-20 19:50:27",
            "endtime": "2020-07-21T02:47:25",
            "frozentime": None,
            "prodsourcelabel": "user",
            "workinggroup": "",
            "vo": "atlas",
            "corecount": 1,
            "tasktype": "anal",
            "processingtype": "panda-client-1.4.32-jedi-run",
            "taskpriority": 1001,
            "currentpriority": 1000,
            "architecture": "x86_64-centos7-gcc8-opt@centos7",
            "transuses": "Atlas-21.2.121",
            "transhome": "AnalysisTransforms-AnalysisBase_21.2.121",
            "transpath": "runGen-00-00-02",
            "lockedby": "",
            "lockedtime": "2020-07-21T02:47:22",
            "termcondition": "Linux-3.10.0-1127.13.1.el7.x86_64-x86_64-with-centos-7.8.2003-Core",
            "splitrule": "US=3,MF=200,RR=1,DE=rucio,IL=1,MO=1,UB=1,IT=1,IA=1,LS=3",
            "walltime": 1,
            "walltimeunit": "kSI2kseconds",
            "outdiskcount": 0,
            "outdiskunit": "kB",
            "workdiskcount": 37,
            "workdiskunit": "MB",
            "ramcount": 1169,
            "ramunit": "MBPerCore",
            "iointensity": 6969,
            "iointensityunit": "kBPerS",
            "workqueue_id": 100,
            "progress": None,
            "failurerate": None,
            "errordialog": "",
            "countrygroup": "de",
            "parent_tid": 21948780,
            "eventservice": "ordinary",
            "ticketid": "",
            "ticketsystemtype": "",
            "statechangetime": "2020-07-21 02:47:25",
            "superstatus": "done",
            "campaign": "",
            "gshare": "User Analysis",
            "cputime": 1,
            "cputimeunit": "",
            "basewalltime": 600,
            "cpuefficiency": 90,
            "nucleus": "",
            "ttcrequested": None,
            "ttcpredicted": None,
            "ttcpredictiondate": None,
            "resquetime": "2020-07-21T01:56:34",
            "requesttype": "",
            "resourcetype": "SCORE",
            "usejumbo": "",
            "diskio": 285,
            "diskiounit": "kBPerS",
            "container_name": "",
            "totevrem": 0,
            "dsinfo": {
                "nfiles": 37,
                "nfilesfinished": 37,
                "nfilesfailed": 0,
                "pctfinished": 100,
                "pctfailed": 0,
            },
            "totev": 2086662,
            "datasets": [
                {
                    "jeditaskid": 21948780,
                    "datasetid": 321963816,
                    "datasetname": "data18_13TeV:data18_13TeV.00349114.physics_Main.deriv.DAOD_SUSY6.r11570_r11571_p3946_p4030_tid19964582_00",
                    "type": "input",
                    "creationtime": "2020-07-20T19:50:27",
                    "modificationtime": "2020-07-21T02:47:22",
                    "vo": "atlas",
                    "cloud": "",
                    "site": "",
                    "masterid": None,
                    "provenanceid": None,
                    "containername": "data18_13TeV.00349114.physics_Main.deriv.DAOD_SUSY6.r11570_r11571_p3946_p4030",
                    "status": "done",
                    "state": "closed",
                    "statechecktime": "2020-07-20T19:50:34",
                    "statecheckexpiration": None,
                    "frozentime": None,
                    "nfiles": 37,
                    "nfilestobeused": 37,
                    "nfilesused": 37,
                    "nevents": 2086662,
                    "neventstobeused": 0,
                    "neventsused": 2086662,
                    "lockedby": "",
                    "lockedtime": None,
                    "nfilesfinished": 37,
                    "nfilesfailed": 0,
                    "attributes": "",
                    "streamname": "IN",
                    "storagetoken": "",
                    "destination": "",
                    "nfilesonhold": 0,
                    "templateid": None,
                },
                {
                    "jeditaskid": 21948780,
                    "datasetid": 322005597,
                    "datasetname": "user.pagessin.r011.grid_data_p4030.00349114_hists.root.322005597",
                    "type": "output",
                    "creationtime": "2020-07-21T00:39:00",
                    "modificationtime": "2020-07-21T02:47:25",
                    "vo": "atlas",
                    "cloud": "",
                    "site": "BNL/SCORE",
                    "masterid": None,
                    "provenanceid": 321963818,
                    "containername": "user.pagessin.r011.grid_data_p4030.00349114_hists.root/",
                    "status": "done",
                    "state": "closed",
                    "statechecktime": "2020-07-21T02:47:24",
                    "statecheckexpiration": None,
                    "frozentime": None,
                    "nfiles": 2,
                    "nfilestobeused": None,
                    "nfilesused": 0,
                    "nevents": 0,
                    "neventstobeused": 0,
                    "neventsused": 0,
                    "lockedby": "",
                    "lockedtime": None,
                    "nfilesfinished": 2,
                    "nfilesfailed": 0,
                    "attributes": "",
                    "streamname": "OUTPUT0",
                    "storagetoken": "",
                    "destination": "BNL/SCORE",
                    "nfilesonhold": 0,
                    "templateid": 321963820,
                },
                {
                    "jeditaskid": 21948780,
                    "datasetid": 322005598,
                    "datasetname": "user.pagessin.r011.grid_data_p4030.00349114_trees.root.322005598",
                    "type": "output",
                    "creationtime": "2020-07-21T00:39:00",
                    "modificationtime": "2020-07-21T02:47:25",
                    "vo": "atlas",
                    "cloud": "",
                    "site": "BNL/SCORE",
                    "masterid": None,
                    "provenanceid": 321963819,
                    "containername": "user.pagessin.r011.grid_data_p4030.00349114_trees.root/",
                    "status": "done",
                    "state": "closed",
                    "statechecktime": "2020-07-21T02:47:25",
                    "statecheckexpiration": None,
                    "frozentime": None,
                    "nfiles": 2,
                    "nfilestobeused": None,
                    "nfilesused": 0,
                    "nevents": 0,
                    "neventstobeused": 0,
                    "neventsused": 0,
                    "lockedby": "",
                    "lockedtime": None,
                    "nfilesfinished": 2,
                    "nfilesfailed": 0,
                    "attributes": "",
                    "streamname": "OUTPUT1",
                    "storagetoken": "",
                    "destination": "BNL/SCORE",
                    "nfilesonhold": 0,
                    "templateid": 321963821,
                },
            ],
        },
        {
            "jeditaskid": 21948716,
            "taskname": "user.pagessin.r011.grid_data_p4030.00348197/",
            "status": "done",
            "username": "Paul Gessinger-Befurt",
            "creationdate": "2020-07-20 19:42:40",
            "modificationtime": "2020-07-21 12:23:01",
            "reqid": 136,
            "oldstatus": "",
            "cloud": "",
            "site": "",
            "starttime": "2020-07-20 19:42:40",
            "endtime": "2020-07-21T12:23:01",
            "frozentime": None,
            "prodsourcelabel": "user",
            "workinggroup": "",
            "vo": "atlas",
            "corecount": 1,
            "tasktype": "anal",
            "processingtype": "panda-client-1.4.32-jedi-run",
            "taskpriority": 1001,
            "currentpriority": 1000,
            "architecture": "x86_64-centos7-gcc8-opt@centos7",
            "transuses": "Atlas-21.2.121",
            "transhome": "AnalysisTransforms-AnalysisBase_21.2.121",
            "transpath": "runGen-00-00-02",
            "lockedby": "",
            "lockedtime": "2020-07-21T12:22:59",
            "termcondition": "Linux-3.10.0-1127.13.1.el7.x86_64-x86_64-with-centos-7.8.2003-Core",
            "splitrule": "US=1,MF=200,RR=1,DE=rucio,IL=1,MO=1,UB=1,IT=1,IA=1,LS=3",
            "walltime": 0,
            "walltimeunit": "",
            "outdiskcount": 500,
            "outdiskunit": "kB",
            "workdiskcount": 0,
            "workdiskunit": "",
            "ramcount": 2000,
            "ramunit": "MBPerCore",
            "iointensity": None,
            "iointensityunit": "",
            "workqueue_id": 100,
            "progress": None,
            "failurerate": None,
            "errordialog": "",
            "countrygroup": "de",
            "parent_tid": 21948716,
            "eventservice": "ordinary",
            "ticketid": "",
            "ticketsystemtype": "",
            "statechangetime": "2020-07-21 12:23:01",
            "superstatus": "done",
            "campaign": "",
            "gshare": "User Analysis",
            "cputime": None,
            "cputimeunit": "",
            "basewalltime": 600,
            "cpuefficiency": 90,
            "nucleus": "",
            "ttcrequested": None,
            "ttcpredicted": None,
            "ttcpredictiondate": None,
            "resquetime": "2020-07-21T11:44:25",
            "requesttype": "",
            "resourcetype": "SCORE",
            "usejumbo": "",
            "diskio": None,
            "diskiounit": "",
            "container_name": "",
            "totevrem": 0,
            "dsinfo": {
                "nfiles": 1,
                "nfilesfinished": 1,
                "nfilesfailed": 0,
                "pctfinished": 100,
                "pctfailed": 0,
            },
            "totev": 188,
            "datasets": [
                {
                    "jeditaskid": 21948716,
                    "datasetid": 321962887,
                    "datasetname": "data18_13TeV:data18_13TeV.00348197.physics_Main.deriv.DAOD_SUSY6.r11570_r11571_p3946_p4030_tid19964539_00",
                    "type": "input",
                    "creationtime": "2020-07-20T19:42:40",
                    "modificationtime": "2020-07-21T12:22:59",
                    "vo": "atlas",
                    "cloud": "",
                    "site": "",
                    "masterid": None,
                    "provenanceid": None,
                    "containername": "data18_13TeV.00348197.physics_Main.deriv.DAOD_SUSY6.r11570_r11571_p3946_p4030",
                    "status": "done",
                    "state": "closed",
                    "statechecktime": "2020-07-20T19:42:42",
                    "statecheckexpiration": None,
                    "frozentime": None,
                    "nfiles": 1,
                    "nfilestobeused": 1,
                    "nfilesused": 1,
                    "nevents": 188,
                    "neventstobeused": 0,
                    "neventsused": 188,
                    "lockedby": "",
                    "lockedtime": None,
                    "nfilesfinished": 1,
                    "nfilesfailed": 0,
                    "attributes": "",
                    "streamname": "IN",
                    "storagetoken": "",
                    "destination": "",
                    "nfilesonhold": 0,
                    "templateid": None,
                },
                {
                    "jeditaskid": 21948716,
                    "datasetid": 322054539,
                    "datasetname": "user.pagessin.r011.grid_data_p4030.00348197_hists.root.322054539",
                    "type": "output",
                    "creationtime": "2020-07-21T12:13:43",
                    "modificationtime": "2020-07-21T12:23:01",
                    "vo": "atlas",
                    "cloud": "",
                    "site": "CA-VICTORIA-WESTGRID-T2/SCORE_HIMEM",
                    "masterid": None,
                    "provenanceid": 321962889,
                    "containername": "user.pagessin.r011.grid_data_p4030.00348197_hists.root/",
                    "status": "done",
                    "state": "closed",
                    "statechecktime": "2020-07-21T12:23:00",
                    "statecheckexpiration": None,
                    "frozentime": None,
                    "nfiles": 1,
                    "nfilestobeused": None,
                    "nfilesused": 0,
                    "nevents": 0,
                    "neventstobeused": 0,
                    "neventsused": 0,
                    "lockedby": "",
                    "lockedtime": None,
                    "nfilesfinished": 1,
                    "nfilesfailed": 0,
                    "attributes": "",
                    "streamname": "OUTPUT0",
                    "storagetoken": "",
                    "destination": "CA-VICTORIA-WESTGRID-T2/SCORE_HIMEM",
                    "nfilesonhold": 0,
                    "templateid": 321962891,
                },
                {
                    "jeditaskid": 21948716,
                    "datasetid": 322054540,
                    "datasetname": "user.pagessin.r011.grid_data_p4030.00348197_trees.root.322054540",
                    "type": "output",
                    "creationtime": "2020-07-21T12:13:43",
                    "modificationtime": "2020-07-21T12:23:01",
                    "vo": "atlas",
                    "cloud": "",
                    "site": "CA-VICTORIA-WESTGRID-T2/SCORE_HIMEM",
                    "masterid": None,
                    "provenanceid": 321962890,
                    "containername": "user.pagessin.r011.grid_data_p4030.00348197_trees.root/",
                    "status": "done",
                    "state": "closed",
                    "statechecktime": "2020-07-21T12:23:00",
                    "statecheckexpiration": None,
                    "frozentime": None,
                    "nfiles": 1,
                    "nfilestobeused": None,
                    "nfilesused": 0,
                    "nevents": 0,
                    "neventstobeused": 0,
                    "neventsused": 0,
                    "lockedby": "",
                    "lockedtime": None,
                    "nfilesfinished": 1,
                    "nfilesfailed": 0,
                    "attributes": "",
                    "streamname": "OUTPUT1",
                    "storagetoken": "",
                    "destination": "CA-VICTORIA-WESTGRID-T2/SCORE_HIMEM",
                    "nfilesonhold": 0,
                    "templateid": 321962892,
                },
            ],
        },
    ],
)
